
#include <MilandrPortDefinitions.h>

/*******************************************
//                                        //
//                PORT                    //
//                DESCRIPTION             //
//                USER DEFINED            //
//                                        //
*******************************************/

/*******************************************
**                HELP                    **
*******************************************/
// In/Out port direction
//   PORT_OE_IN                 0x0
//   PORT_OE_OUT                0x1
//
// Port Functional Mode
//   PORT_FUNC_PORT             0x0
//   PORT_FUNC_MAIN             0x1
//   PORT_FUNC_ALTER            0x2
//   PORT_FUNC_OVERRID          0x3
//
// Analog/Digital
//   PORT_MODE_ANALOG           0x0
//   PORT_MODE_DIGITAL          0x1
//
// PullUp On/Off
//   PORT_PULL_UP_OFF           0x0
//   PORT_PULL_UP_ON            0x1
//
// PullDown On/Off
//   PORT_PULL_DOWN_OFF         0x0
//   PORT_PULL_DOWN_ON          0x1
//
// Shmidt Filter Histeresis
//   PORT_PD_SHM_OFF            0x0
//   PORT_PD_SHM_ON             0x1
//
// Driver Regime
//   PORT_PD_DRIVER             0x0
//   PORT_PD_OPEN               0x1
//
// Output Transmitter Mode
//   PORT_OUTPUT_OFF            0x0
//   PORT_SPEED_SLOW            0x1
//   PORT_SPEED_FAST            0x2
//   PORT_SPEED_MAXFAST         0x3
//
// Port Filter
//   PORT_GFEN_OFF              0x0
//   PORT_GFEN_ON               0x1

#ifdef PORT_A_PINS_INIT
//                                            |In/Out      | MODE          | Analog/digital  | PullUp On/Off   | PullDown On/Off   | ShmidtF Hist   | Driver_PD     | Transmitter    | Filter        |
        #define PORT_A_00_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_A_01_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_A_02_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_A_03_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)

        #define PORT_A_04_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_A_05_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_A_06_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_A_07_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)

        #define PORT_A_08_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_A_09_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_A_10_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_A_11_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)

        #define PORT_A_12_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_A_13_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_A_14_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_A_15_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)

        #ifdef PORT_A_RXTX_INIT
                #define PORT_A_RXTX_INIT_NUM    0x0000
        #endif
#endif
#ifdef PORT_B_PINS_INIT
//                                   |In/Out    | MODE          | Analog/digital  | PullUp On/Off   | PullDown On/Off   | ShmidtF Hist   | Driver_PD     | Transmitter    | Filter        |
        #define PORT_B_00_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_B_01_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_B_02_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_B_03_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)

        #define PORT_B_04_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_B_05_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_B_06_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_B_07_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)

        #define PORT_B_08_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_B_09_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_B_10_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_B_11_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)

        #define PORT_B_12_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_B_13_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_B_14_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_B_15_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)

        #ifdef PORT_B_RXTX_INIT
                #define PORT_B_RXTX_INIT_NUM    0x0000
        #endif
#endif
#ifdef PORT_C_PINS_INIT
//                                            |In/Out    | MODE             | Analog/digital   | PullUp On/Off   | PullDown On/Off   | ShmidtF Hist   | Driver_PD     | Transmitter    | Filter        |
        #define PORT_C_00_DEF DEFINE_PORT_PIN(PORT_OE_OUT, PORT_FUNC_PORT,      PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_C_01_DEF DEFINE_PORT_PIN(PORT_OE_OUT, PORT_FUNC_PORT,      PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_C_02_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PORT_FUNC_PORT,      PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF,    PORT_GFEN_OFF)
        #define PORT_C_03_DEF DEFINE_PORT_PIN(PORT_OE_OUT, PORT_FUNC_MAIN,      PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)

        #define PORT_C_04_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PORT_FUNC_MAIN,      PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_C_05_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PORT_FUNC_PORT,      PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF,    PORT_GFEN_OFF)
        #define PORT_C_06_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PORT_FUNC_PORT,      PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF,    PORT_GFEN_OFF)
        #define PORT_C_07_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PORT_FUNC_PORT,      PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF,    PORT_GFEN_OFF)

        #define PORT_C_08_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PORT_FUNC_PORT,      PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF,    PORT_GFEN_OFF)
        #define PORT_C_09_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PORT_FUNC_PORT,      PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF,    PORT_GFEN_OFF)
        #define PORT_C_10_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PORT_FUNC_PORT,      PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF,    PORT_GFEN_OFF)
        #define PORT_C_11_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PORT_FUNC_PORT,      PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF,    PORT_GFEN_OFF)

        #define PORT_C_12_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PORT_FUNC_PORT,      PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF,    PORT_GFEN_OFF)
        #define PORT_C_13_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PC13_M01_PRMA_PLUS,  PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_ON, PORT_PD_SHM_ON, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_C_14_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PC14_M01_PRMA_MINUS, PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_ON, PORT_PD_SHM_ON, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_C_15_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PC15_M01_PRMB_PLUS,  PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)


        #ifdef PORT_C_RXTX_INIT
                #define PORT_C_RXTX_INIT_NUM    0x0000
        #endif
#endif
#ifdef PORT_D_PINS_INIT
//                                   |In/Out    | MODE          | Analog/digital  | PullUp On/Off   | PullDown On/Off   | ShmidtF Hist   | Driver_PD     | Transmitter    | Filter        |
        #define PORT_D_00_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PD00_M01_PRMB_MINUS, PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_D_01_DEF DEFINE_PORT_PIN(PORT_OE_OUT, PD01_M01_PRDA_PLUS,  PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_D_02_DEF DEFINE_PORT_PIN(PORT_OE_OUT, PD02_M01_PRDA_MINUS, PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_D_03_DEF DEFINE_PORT_PIN(PORT_OE_OUT, PD03_M01_PRDB_PLUS,  PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)

        #define PORT_D_04_DEF DEFINE_PORT_PIN(PORT_OE_OUT, PD04_M01_PRDB_MINUS, PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_D_05_DEF DEFINE_PORT_PIN(PORT_OE_OUT, PD05_M01_PRD_PRMA,   PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_D_06_DEF DEFINE_PORT_PIN(PORT_OE_OUT, PD06_M01_PRD_PRMB,   PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_D_07_DEF DEFINE_PORT_PIN(PORT_OE_OUT, PORT_FUNC_PORT,      PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)

        #define PORT_D_08_DEF DEFINE_PORT_PIN(PORT_OE_OUT, PORT_FUNC_PORT,      PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_D_09_DEF DEFINE_PORT_PIN(PORT_OE_OUT, PORT_FUNC_PORT,      PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_D_10_DEF DEFINE_PORT_PIN(PORT_OE_OUT, PORT_FUNC_PORT,      PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_D_11_DEF DEFINE_PORT_PIN(PORT_OE_OUT, PORT_FUNC_PORT,      PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)

        #define PORT_D_12_DEF DEFINE_PORT_PIN(PORT_OE_OUT, PORT_FUNC_PORT,      PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_D_13_DEF DEFINE_PORT_PIN(PORT_OE_OUT, PORT_FUNC_PORT,      PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_D_14_DEF DEFINE_PORT_PIN(PORT_OE_OUT, PORT_FUNC_PORT,      PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_D_15_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PORT_FUNC_PORT,      PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF,    PORT_GFEN_OFF)


        #ifdef PORT_D_RXTX_INIT
                #define PORT_D_RXTX_INIT_NUM    0x0000
        #endif
#endif
#ifdef PORT_E_PINS_INIT
//                                   |In/Out    | MODE          | Analog/digital  | PullUp On/Off   | PullDown On/Off   | ShmidtF Hist   | Driver_PD     | Transmitter    | Filter        |
        #define PORT_E_00_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_E_01_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_E_02_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_E_03_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)

        #define PORT_E_04_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_E_05_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_E_06_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_E_07_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)

        #define PORT_E_08_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_E_09_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_E_10_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_E_11_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)

        #define PORT_E_12_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_E_13_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_E_14_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF, PORT_GFEN_OFF)
        #define PORT_E_15_DEF DEFINE_PORT_PIN(PORT_OE_IN, PORT_FUNC_PORT, PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)


        #ifdef PORT_E_RXTX_INIT
                #define PORT_E_RXTX_INIT_NUM    0x0000
        #endif
#endif
#ifdef PORT_F_PINS_INIT
//                                           |In/Out    | MODE          | Analog/digital  | PullUp On/Off   | PullDown On/Off   | ShmidtF Hist   | Driver_PD     | Transmitter    | Filter        |
        #define PORT_F_00_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PORT_FUNC_PORT,      PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF,    PORT_GFEN_OFF)
        #define PORT_F_01_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PORT_FUNC_PORT,      PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF,    PORT_GFEN_OFF)
        #define PORT_F_02_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PORT_FUNC_PORT,      PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF,    PORT_GFEN_OFF)
        #define PORT_F_03_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PF03_M01_PRMC_PLUS,  PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_ON, PORT_PD_SHM_ON, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)

        #define PORT_F_04_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PF04_M01_PRMC_MINUS, PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_ON, PORT_PD_SHM_ON, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_F_05_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PF05_M01_PRMD_PLUS,  PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_F_06_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PF06_M01_PRMD_MINUS, PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_F_07_DEF DEFINE_PORT_PIN(PORT_OE_OUT, PF07_M01_PRDC_PLUS,  PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)

        #define PORT_F_08_DEF DEFINE_PORT_PIN(PORT_OE_OUT, PF08_M01_PRDC_MINUS, PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_F_09_DEF DEFINE_PORT_PIN(PORT_OE_OUT, PF09_M01_PRDD_PLUS,  PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_F_10_DEF DEFINE_PORT_PIN(PORT_OE_OUT, PF10_M01_PRDD_MINUS, PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_F_11_DEF DEFINE_PORT_PIN(PORT_OE_OUT, PF11_M01_PRD_PRMC,   PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)

        #define PORT_F_12_DEF DEFINE_PORT_PIN(PORT_OE_OUT, PF12_M01_PRD_PRMD,   PORT_MODE_DIGITAL, PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_SPEED_MAXFAST, PORT_GFEN_OFF)
        #define PORT_F_13_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PORT_FUNC_PORT,      PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF,    PORT_GFEN_OFF)
        #define PORT_F_14_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PORT_FUNC_PORT,      PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF,    PORT_GFEN_OFF)
        #define PORT_F_15_DEF DEFINE_PORT_PIN(PORT_OE_IN,  PORT_FUNC_PORT,      PORT_DUMMY_MODE,   PORT_PULL_UP_OFF, PORT_PULL_DOWN_OFF, PORT_PD_SHM_OFF, PORT_PD_DRIVER, PORT_OUTPUT_OFF,    PORT_GFEN_OFF)




        #ifdef PORT_F_RXTX_INIT
                #define PORT_F_RXTX_INIT_NUM    0x0000
        #endif
#endif


/*******************************************
**                                        **
**    Device Configuration || DEFINES     **
**                                        **
*******************************************/

// REAL DEVICE PROPER CONFIGURATION ( BRIEF )
#define REAL_DEVICE_PORT_A_RXTX_INIT_NUM  0x0000

#define REAL_DEVICE_PORTA_OE            0x0000
#define REAL_DEVICE_PORTA_FUNC          0x00000000
#define REAL_DEVICE_PORTA_ANALOG        0x0000
#define REAL_DEVICE_PORTA_PULL          0x00000000
#define REAL_DEVICE_PORTA_PD            0x00000000
#define REAL_DEVICE_PORTA_PWR           0x00000000
#define REAL_DEVICE_PORTA_GFEN          0x0000

#define REAL_DEVICE_PORT_B_RXTX_INIT_NUM  0x0000

#define REAL_DEVICE_PORTB_OE            0x0000
#define REAL_DEVICE_PORTB_FUNC          0x00000000
#define REAL_DEVICE_PORTB_ANALOG        0x0000
#define REAL_DEVICE_PORTB_PULL          0x00000000
#define REAL_DEVICE_PORTB_PD            0x00000000
#define REAL_DEVICE_PORTB_PWR           0x00000000
#define REAL_DEVICE_PORTB_GFEN          0x0000

#define REAL_DEVICE_PORT_C_RXTX_INIT_NUM  0x0000

#define REAL_DEVICE_PORTC_OE            0x0000
#define REAL_DEVICE_PORTC_FUNC          0x00000000
#define REAL_DEVICE_PORTC_ANALOG        0x0000
#define REAL_DEVICE_PORTC_PULL          0x00000000
#define REAL_DEVICE_PORTC_PD            0x00000000
#define REAL_DEVICE_PORTC_PWR           0x00000000
#define REAL_DEVICE_PORTC_GFEN          0x0000

#define REAL_DEVICE_PORT_D_RXTX_INIT_NUM  0x0000

#define REAL_DEVICE_PORTD_OE            0x0000
#define REAL_DEVICE_PORTD_FUNC          0x00000000
#define REAL_DEVICE_PORTD_ANALOG        0x0000
#define REAL_DEVICE_PORTD_PULL          0x00000000
#define REAL_DEVICE_PORTD_PD            0x00000000
#define REAL_DEVICE_PORTD_PWR           0x00000000
#define REAL_DEVICE_PORTD_GFEN          0x0000

#define REAL_DEVICE_PORT_E_RXTX_INIT_NUM  0x0000

#define REAL_DEVICE_PORTE_OE            0x0000
#define REAL_DEVICE_PORTE_FUNC          0x00000000
#define REAL_DEVICE_PORTE_ANALOG        0x0000
#define REAL_DEVICE_PORTE_PULL          0x00000000
#define REAL_DEVICE_PORTE_PD            0x00000000
#define REAL_DEVICE_PORTE_PWR           0x00000000
#define REAL_DEVICE_PORTE_GFEN          0x0000

#define REAL_DEVICE_PORT_F_RXTX_INIT_NUM  0x0000

#define REAL_DEVICE_PORTF_OE            0x0000
#define REAL_DEVICE_PORTF_FUNC          0x00000000
#define REAL_DEVICE_PORTF_ANALOG        0x0000
#define REAL_DEVICE_PORTF_PULL          0x00000000
#define REAL_DEVICE_PORTF_PD            0x00000000
#define REAL_DEVICE_PORTF_PWR           0x00000000
#define REAL_DEVICE_PORTF_GFEN          0x0000


// RELEASE CONF FOR PERFORMANCE TESTS ON THE BOARD

#define TESTBOARD_PORT_A_RXTX_INIT_NUM  0x0000

#define TESTBOARD_PORTA_OE              0x00FF
#define TESTBOARD_PORTA_FUNC            0x00000000
#define TESTBOARD_PORTA_ANALOG          0xFFFF
#define TESTBOARD_PORTA_PULL            0x00000000
#define TESTBOARD_PORTA_PD              0x00000000
#define TESTBOARD_PORTA_PWR             0x0000AAAA
#define TESTBOARD_PORTA_GFEN            0x0000

#define TESTBOARD_PORT_B_RXTX_INIT_NUM  0x0000

#define TESTBOARD_PORTB_OE              0x0000
#define TESTBOARD_PORTB_FUNC            0x00000000
#define TESTBOARD_PORTB_ANALOG          0xFFFF
#define TESTBOARD_PORTB_PULL            0x00000000
#define TESTBOARD_PORTB_PD              0x00000000
#define TESTBOARD_PORTB_PWR             0x00000000
#define TESTBOARD_PORTB_GFEN            0x0000

#define TESTBOARD_PORT_C_RXTX_INIT_NUM  0x0000    // watch it

#define TESTBOARD_PORTC_OE              0x000F
#define TESTBOARD_PORTC_FUNC            0x14000145
#define TESTBOARD_PORTC_ANALOG          0xFFFF
#define TESTBOARD_PORTC_PULL            0x0000FFE0
#define TESTBOARD_PORTC_PD              0x60100000
#define TESTBOARD_PORTC_PWR             0x000000AA
#define TESTBOARD_PORTC_GFEN            0x0000

#define TESTBOARD_PORT_D_RXTX_INIT_NUM  0x0000

#define TESTBOARD_PORTD_OE              0x8026
#define TESTBOARD_PORTD_FUNC            0x82000414
#define TESTBOARD_PORTD_ANALOG          0xFFFF
#define TESTBOARD_PORTD_PULL            0x00007FC9
#define TESTBOARD_PORTD_PD              0x10000000
#define TESTBOARD_PORTD_PWR             0x80000828
#define TESTBOARD_PORTD_GFEN            0x0000

#define TESTBOARD_PORT_E_RXTX_INIT_NUM  0x0000

#define TESTBOARD_PORTE_OE              0x0000
#define TESTBOARD_PORTE_FUNC            0x00000000
#define TESTBOARD_PORTE_ANALOG          0xFFFF
#define TESTBOARD_PORTE_PULL            0x00000000
#define TESTBOARD_PORTE_PD              0x00000000
#define TESTBOARD_PORTE_PWR             0x40550400
#define TESTBOARD_PORTE_GFEN            0x0000

#define TESTBOARD_PORT_F_RXTX_INIT_NUM  0x0000

#define TESTBOARD_PORTF_OE              0x0000
#define TESTBOARD_PORTF_FUNC            0x00000000
#define TESTBOARD_PORTF_ANALOG          0xFFFF
#define TESTBOARD_PORTF_PULL            0x00000000
#define TESTBOARD_PORTF_PD              0x00000000
#define TESTBOARD_PORTF_PWR             0xFFFFFFFF
#define TESTBOARD_PORTF_GFEN            0x0000






/************************************
**                                 **
**   CONFIGURATION INFRASTRUCTURE  **
**                                 **
************************************/



#ifdef PORT_A_PINS_INIT
#define ASSEMBLE_BITS_PORT_A( mask__, shift__, port_mul__ ) ASSEMBLE_BITS(PORT_A_00_DEF,PORT_A_01_DEF,PORT_A_02_DEF,PORT_A_03_DEF,PORT_A_04_DEF,PORT_A_05_DEF,PORT_A_06_DEF,PORT_A_07_DEF,PORT_A_08_DEF,PORT_A_09_DEF,PORT_A_10_DEF,PORT_A_11_DEF,PORT_A_12_DEF,PORT_A_13_DEF,PORT_A_14_DEF,PORT_A_15_DEF,mask__,shift__,port_mul__)

#define PORT_A_OE               ASSEMBLE_BITS_PORT_A(PORTDEF_MASK_OE,           PORTDEF_SHIFT_OE,               PORT_NUM_MUL_X1)
#define PORT_A_FUNC             ASSEMBLE_BITS_PORT_A(PORTDEF_MASK_FUNC,         PORTDEF_SHIFT_FUNC,             PORT_NUM_MUL_X2)
#define PORT_A_AD               ASSEMBLE_BITS_PORT_A(PORTDEF_MASK_AD,           PORTDEF_SHIFT_AD,               PORT_NUM_MUL_X1)

#define PORT_A_PULL_UP          ASSEMBLE_BITS_PORT_A(PORTDEF_MASK_PULL_UP,      PORTDEF_SHIFT_PULL_UP,          PORT_NUM_MUL_X1)
#define PORT_A_PULL_DOWN        ASSEMBLE_BITS_PORT_A(PORTDEF_MASK_PULL_DOWN,    PORTDEF_SHIFT_PULL_DOWN,        PORT_NUM_MUL_X1)
#define PORT_A_PULL             (PORT_A_PULL_DOWN | ( PORT_A_PULL_UP << HALF_WORD ))

#define PORT_A_HIST             ASSEMBLE_BITS_PORT_A(PORTDEF_MASK_HIST,         PORTDEF_SHIFT_HIST,             PORT_NUM_MUL_X1)
#define PORT_A_PD_DRIVER        ASSEMBLE_BITS_PORT_A(PORTDEF_MASK_PD,           PORTDEF_SHIFT_PD,               PORT_NUM_MUL_X1)
#define PORT_A_PD               (PORT_A_PD_DRIVER | ( PORT_A_HIST << HALF_WORD ))

#define PORT_A_PWR              ASSEMBLE_BITS_PORT_A(PORTDEF_MASK_PWR,          PORTDEF_SHIFT_PWR,              PORT_NUM_MUL_X2)
#define PORT_A_GFEN             ASSEMBLE_BITS_PORT_A(PORTDEF_MASK_GFEN,         PORTDEF_SHIFT_GFEN,             PORT_NUM_MUL_X1)

#endif // End of PORT_B_PINS_INIT

#ifdef PORT_B_PINS_INIT
#define ASSEMBLE_BITS_PORT_B( mask__, shift__, port_mul__ ) ASSEMBLE_BITS(PORT_B_00_DEF,PORT_B_01_DEF,PORT_B_02_DEF,PORT_B_03_DEF,PORT_B_04_DEF,PORT_B_05_DEF,PORT_B_06_DEF,PORT_B_07_DEF,PORT_B_08_DEF,PORT_B_09_DEF,PORT_B_10_DEF,PORT_B_11_DEF,PORT_B_12_DEF,PORT_B_13_DEF,PORT_B_14_DEF,PORT_B_15_DEF,mask__,shift__,port_mul__)

#define PORT_B_OE               ASSEMBLE_BITS_PORT_B(PORTDEF_MASK_OE,           PORTDEF_SHIFT_OE,               PORT_NUM_MUL_X1)
#define PORT_B_FUNC             ASSEMBLE_BITS_PORT_B(PORTDEF_MASK_FUNC,         PORTDEF_SHIFT_FUNC,             PORT_NUM_MUL_X2)
#define PORT_B_AD               ASSEMBLE_BITS_PORT_B(PORTDEF_MASK_AD,           PORTDEF_SHIFT_AD,               PORT_NUM_MUL_X1)

#define PORT_B_PULL_UP          ASSEMBLE_BITS_PORT_B(PORTDEF_MASK_PULL_UP,      PORTDEF_SHIFT_PULL_UP,          PORT_NUM_MUL_X1)
#define PORT_B_PULL_DOWN        ASSEMBLE_BITS_PORT_B(PORTDEF_MASK_PULL_DOWN,    PORTDEF_SHIFT_PULL_DOWN,        PORT_NUM_MUL_X1)
#define PORT_B_PULL             (PORT_B_PULL_DOWN | ( PORT_B_PULL_UP << HALF_WORD ))

#define PORT_B_HIST             ASSEMBLE_BITS_PORT_B(PORTDEF_MASK_HIST,         PORTDEF_SHIFT_HIST,             PORT_NUM_MUL_X1)
#define PORT_B_PD_DRIVER        ASSEMBLE_BITS_PORT_B(PORTDEF_MASK_PD,           PORTDEF_SHIFT_PD,               PORT_NUM_MUL_X1)
#define PORT_B_PD               (PORT_B_PD_DRIVER | ( PORT_B_HIST << HALF_WORD ))

#define PORT_B_PWR              ASSEMBLE_BITS_PORT_B(PORTDEF_MASK_PWR,          PORTDEF_SHIFT_PWR,              PORT_NUM_MUL_X2)
#define PORT_B_GFEN             ASSEMBLE_BITS_PORT_B(PORTDEF_MASK_GFEN,         PORTDEF_SHIFT_GFEN,             PORT_NUM_MUL_X1)

#endif // End of PORT_B_PINS_INIT

#ifdef PORT_C_PINS_INIT
#define ASSEMBLE_BITS_PORT_C( mask__, shift__, port_mul__ ) ASSEMBLE_BITS(PORT_C_00_DEF,PORT_C_01_DEF,PORT_C_02_DEF,PORT_C_03_DEF,PORT_C_04_DEF,PORT_C_05_DEF,PORT_C_06_DEF,PORT_C_07_DEF,PORT_C_08_DEF,PORT_C_09_DEF,PORT_C_10_DEF,PORT_C_11_DEF,PORT_C_12_DEF,PORT_C_13_DEF,PORT_C_14_DEF,PORT_C_15_DEF,mask__,shift__,port_mul__)

#define PORT_C_OE               ASSEMBLE_BITS_PORT_C(PORTDEF_MASK_OE,           PORTDEF_SHIFT_OE,               PORT_NUM_MUL_X1)
#define PORT_C_FUNC             ASSEMBLE_BITS_PORT_C(PORTDEF_MASK_FUNC,         PORTDEF_SHIFT_FUNC,             PORT_NUM_MUL_X2)
#define PORT_C_AD               ASSEMBLE_BITS_PORT_C(PORTDEF_MASK_AD,           PORTDEF_SHIFT_AD,               PORT_NUM_MUL_X1)

#define PORT_C_PULL_UP          ASSEMBLE_BITS_PORT_C(PORTDEF_MASK_PULL_UP,      PORTDEF_SHIFT_PULL_UP,          PORT_NUM_MUL_X1)
#define PORT_C_PULL_DOWN        ASSEMBLE_BITS_PORT_C(PORTDEF_MASK_PULL_DOWN,    PORTDEF_SHIFT_PULL_DOWN,        PORT_NUM_MUL_X1)
#define PORT_C_PULL             (PORT_C_PULL_DOWN | ( PORT_C_PULL_UP << HALF_WORD ))

#define PORT_C_HIST             ASSEMBLE_BITS_PORT_C(PORTDEF_MASK_HIST,         PORTDEF_SHIFT_HIST,             PORT_NUM_MUL_X1)
#define PORT_C_PD_DRIVER        ASSEMBLE_BITS_PORT_C(PORTDEF_MASK_PD,           PORTDEF_SHIFT_PD,               PORT_NUM_MUL_X1)
#define PORT_C_PD               (PORT_C_PD_DRIVER | ( PORT_C_HIST << HALF_WORD ))

#define PORT_C_PWR              ASSEMBLE_BITS_PORT_C(PORTDEF_MASK_PWR,          PORTDEF_SHIFT_PWR,              PORT_NUM_MUL_X2)
#define PORT_C_GFEN             ASSEMBLE_BITS_PORT_C(PORTDEF_MASK_GFEN,         PORTDEF_SHIFT_GFEN,             PORT_NUM_MUL_X1)

#endif // End of PORT_C_PINS_INIT

#ifdef PORT_D_PINS_INIT
#define ASSEMBLE_BITS_PORT_D( mask__, shift__, port_mul__ ) ASSEMBLE_BITS(PORT_D_00_DEF,PORT_D_01_DEF,PORT_D_02_DEF,PORT_D_03_DEF,PORT_D_04_DEF,PORT_D_05_DEF,PORT_D_06_DEF,PORT_D_07_DEF,PORT_D_08_DEF,PORT_D_09_DEF,PORT_D_10_DEF,PORT_D_11_DEF,PORT_D_12_DEF,PORT_D_13_DEF,PORT_D_14_DEF,PORT_D_15_DEF,mask__,shift__,port_mul__)

#define PORT_D_OE               ASSEMBLE_BITS_PORT_D(PORTDEF_MASK_OE,           PORTDEF_SHIFT_OE,               PORT_NUM_MUL_X1)
#define PORT_D_FUNC             ASSEMBLE_BITS_PORT_D(PORTDEF_MASK_FUNC,         PORTDEF_SHIFT_FUNC,             PORT_NUM_MUL_X2)
#define PORT_D_AD               ASSEMBLE_BITS_PORT_D(PORTDEF_MASK_AD,           PORTDEF_SHIFT_AD,               PORT_NUM_MUL_X1)

#define PORT_D_PULL_UP          ASSEMBLE_BITS_PORT_D(PORTDEF_MASK_PULL_UP,      PORTDEF_SHIFT_PULL_UP,          PORT_NUM_MUL_X1)
#define PORT_D_PULL_DOWN        ASSEMBLE_BITS_PORT_D(PORTDEF_MASK_PULL_DOWN,    PORTDEF_SHIFT_PULL_DOWN,        PORT_NUM_MUL_X1)
#define PORT_D_PULL             (PORT_D_PULL_DOWN | ( PORT_D_PULL_UP << HALF_WORD ))

#define PORT_D_HIST             ASSEMBLE_BITS_PORT_D(PORTDEF_MASK_HIST,         PORTDEF_SHIFT_HIST,             PORT_NUM_MUL_X1)
#define PORT_D_PD_DRIVER        ASSEMBLE_BITS_PORT_D(PORTDEF_MASK_PD,           PORTDEF_SHIFT_PD,               PORT_NUM_MUL_X1)
#define PORT_D_PD               (PORT_D_PD_DRIVER | ( PORT_D_HIST << HALF_WORD ))

#define PORT_D_PWR              ASSEMBLE_BITS_PORT_D(PORTDEF_MASK_PWR,          PORTDEF_SHIFT_PWR,              PORT_NUM_MUL_X2)
#define PORT_D_GFEN             ASSEMBLE_BITS_PORT_D(PORTDEF_MASK_GFEN,         PORTDEF_SHIFT_GFEN,             PORT_NUM_MUL_X1)

#endif // End of PORT_D_PINS_INIT

#ifdef PORT_E_PINS_INIT
#define ASSEMBLE_BITS_PORT_E( mask__, shift__, port_mul__ ) ASSEMBLE_BITS(PORT_E_00_DEF,PORT_E_01_DEF,PORT_E_02_DEF,PORT_E_03_DEF,PORT_E_04_DEF,PORT_E_05_DEF,PORT_E_06_DEF,PORT_E_07_DEF,PORT_E_08_DEF,PORT_E_09_DEF,PORT_E_10_DEF,PORT_E_11_DEF,PORT_E_12_DEF,PORT_E_13_DEF,PORT_E_14_DEF,PORT_E_15_DEF,mask__,shift__,port_mul__)

#define PORT_E_OE               ASSEMBLE_BITS_PORT_E(PORTDEF_MASK_OE,           PORTDEF_SHIFT_OE,               PORT_NUM_MUL_X1)
#define PORT_E_FUNC             ASSEMBLE_BITS_PORT_E(PORTDEF_MASK_FUNC,         PORTDEF_SHIFT_FUNC,             PORT_NUM_MUL_X2)
#define PORT_E_AD               ASSEMBLE_BITS_PORT_E(PORTDEF_MASK_AD,           PORTDEF_SHIFT_AD,               PORT_NUM_MUL_X1)

#define PORT_E_PULL_UP          ASSEMBLE_BITS_PORT_E(PORTDEF_MASK_PULL_UP,      PORTDEF_SHIFT_PULL_UP,          PORT_NUM_MUL_X1)
#define PORT_E_PULL_DOWN        ASSEMBLE_BITS_PORT_E(PORTDEF_MASK_PULL_DOWN,    PORTDEF_SHIFT_PULL_DOWN,        PORT_NUM_MUL_X1)
#define PORT_E_PULL             (PORT_E_PULL_DOWN | ( PORT_E_PULL_UP << HALF_WORD ))

#define PORT_E_HIST             ASSEMBLE_BITS_PORT_E(PORTDEF_MASK_HIST,         PORTDEF_SHIFT_HIST,             PORT_NUM_MUL_X1)
#define PORT_E_PD_DRIVER        ASSEMBLE_BITS_PORT_E(PORTDEF_MASK_PD,           PORTDEF_SHIFT_PD,               PORT_NUM_MUL_X1)
#define PORT_E_PD               (PORT_E_PD_DRIVER | ( PORT_E_HIST << HALF_WORD ))

#define PORT_E_PWR              ASSEMBLE_BITS_PORT_E(PORTDEF_MASK_PWR,          PORTDEF_SHIFT_PWR,              PORT_NUM_MUL_X2)
#define PORT_E_GFEN             ASSEMBLE_BITS_PORT_E(PORTDEF_MASK_GFEN,         PORTDEF_SHIFT_GFEN,             PORT_NUM_MUL_X1)

#endif // End of PORT_F_PINS_INIT

#ifdef PORT_F_PINS_INIT
#define ASSEMBLE_BITS_PORT_F( mask__, shift__, port_mul__ ) ASSEMBLE_BITS(PORT_F_00_DEF,PORT_F_01_DEF,PORT_F_02_DEF,PORT_F_03_DEF,PORT_F_04_DEF,PORT_F_05_DEF,PORT_F_06_DEF,PORT_F_07_DEF,PORT_F_08_DEF,PORT_F_09_DEF,PORT_F_10_DEF,PORT_F_11_DEF,PORT_F_12_DEF,PORT_F_13_DEF,PORT_F_14_DEF,PORT_F_15_DEF,mask__,shift__,port_mul__)

#define PORT_F_OE               ASSEMBLE_BITS_PORT_F(PORTDEF_MASK_OE,           PORTDEF_SHIFT_OE,               PORT_NUM_MUL_X1)         // !
#define PORT_F_FUNC             ASSEMBLE_BITS_PORT_F(PORTDEF_MASK_FUNC,         PORTDEF_SHIFT_FUNC,             PORT_NUM_MUL_X2)         // !
#define PORT_F_AD               ASSEMBLE_BITS_PORT_F(PORTDEF_MASK_AD,           PORTDEF_SHIFT_AD,               PORT_NUM_MUL_X1)         // !

#define PORT_F_PULL_UP          ASSEMBLE_BITS_PORT_F(PORTDEF_MASK_PULL_UP,      PORTDEF_SHIFT_PULL_UP,          PORT_NUM_MUL_X1)
#define PORT_F_PULL_DOWN        ASSEMBLE_BITS_PORT_F(PORTDEF_MASK_PULL_DOWN,    PORTDEF_SHIFT_PULL_DOWN,        PORT_NUM_MUL_X1)
#define PORT_F_PULL             (PORT_F_PULL_DOWN | ( PORT_F_PULL_UP << HALF_WORD ))                                                     // !

#define PORT_F_HIST             ASSEMBLE_BITS_PORT_F(PORTDEF_MASK_HIST,         PORTDEF_SHIFT_HIST,             PORT_NUM_MUL_X1)
#define PORT_F_PD_DRIVER        ASSEMBLE_BITS_PORT_F(PORTDEF_MASK_PD,           PORTDEF_SHIFT_PD,               PORT_NUM_MUL_X1)
#define PORT_F_PD               (PORT_F_PD_DRIVER | ( PORT_F_HIST << HALF_WORD ))                                                        // !

#define PORT_F_PWR              ASSEMBLE_BITS_PORT_F(PORTDEF_MASK_PWR,          PORTDEF_SHIFT_PWR,              PORT_NUM_MUL_X2)         // !
#define PORT_F_GFEN             ASSEMBLE_BITS_PORT_F(PORTDEF_MASK_GFEN,         PORTDEF_SHIFT_GFEN,             PORT_NUM_MUL_X1)         // !

#endif // End of PORT_F_PINS_INIT


void assemblePorts()
{
#ifdef TEST_BOARD_RELEASE
        #ifdef PORT_A_PINS_INIT
                MDR_PORTA->OE     = TESTBOARD_PORTA_OE;
                MDR_PORTA->FUNC   = TESTBOARD_PORTA_FUNC;
                MDR_PORTA->ANALOG = TESTBOARD_PORTA_ANALOG;
                MDR_PORTA->PULL   = TESTBOARD_PORTA_PULL;
                MDR_PORTA->PD     = TESTBOARD_PORTA_PD;
                MDR_PORTA->PWR    = TESTBOARD_PORTA_PWR;
                MDR_PORTA->GFEN   = TESTBOARD_PORTA_GFEN;

                #ifdef PORT_A_RXTX_INIT
                        MDR_PORTA->RXTX = TESTBOARD_PORT_A_RXTX_INIT_NUM;
                #endif
        #endif // End of PORT_A_PINS_INIT


        #ifdef PORT_B_PINS_INIT
                MDR_PORTB->OE     = TESTBOARD_PORTB_OE;
                MDR_PORTB->FUNC   = TESTBOARD_PORTB_FUNC;
                MDR_PORTB->ANALOG = TESTBOARD_PORTB_ANALOG;
                MDR_PORTB->PULL   = TESTBOARD_PORTB_PULL;
                MDR_PORTB->PD     = TESTBOARD_PORTB_PD;
                MDR_PORTB->PWR    = TESTBOARD_PORTB_PWR;
                MDR_PORTB->GFEN   = TESTBOARD_PORTB_GFEN;

                #ifdef PORT_B_RXTX_INIT
                        MDR_PORTB->RXTX = TESTBOARD_PORT_B_RXTX_INIT_NUM;
                #endif
        #endif // End of PORT_B_PINS_INIT


        #ifdef PORT_C_PINS_INIT
        //MDR_PORTC->RXTX   =
                MDR_PORTC->OE     = TESTBOARD_PORTC_OE;
                MDR_PORTC->FUNC   = TESTBOARD_PORTC_FUNC;
                MDR_PORTC->ANALOG = TESTBOARD_PORTC_ANALOG;
                MDR_PORTC->PULL   = TESTBOARD_PORTC_PULL;
                MDR_PORTC->PD     = TESTBOARD_PORTC_PD;
                MDR_PORTC->PWR    = TESTBOARD_PORTC_PWR;
                MDR_PORTC->GFEN   = TESTBOARD_PORTC_GFEN;

                #ifdef PORT_C_RXTX_INIT
                        MDR_PORTC->RXTX = TESTBOARD_PORT_C_RXTX_INIT_NUM;
                #endif
        #endif // End of PORT_C_PINS_INIT


        #ifdef PORT_D_PINS_INIT
                MDR_PORTD->OE     = TESTBOARD_PORTD_OE;
                MDR_PORTD->FUNC   = TESTBOARD_PORTD_FUNC;
                MDR_PORTD->ANALOG = TESTBOARD_PORTD_ANALOG;
                MDR_PORTD->PULL   = TESTBOARD_PORTD_PULL;
                MDR_PORTD->PD     = TESTBOARD_PORTD_PD;
                MDR_PORTD->PWR    = TESTBOARD_PORTD_PWR;
                MDR_PORTD->GFEN   = TESTBOARD_PORTD_GFEN;

                #ifdef PORT_D_RXTX_INIT
                        MDR_PORTD->RXTX = TESTBOARD_PORT_D_RXTX_INIT_NUM;
                #endif
        #endif // End of PORT_D_PINS_INIT


        #ifdef PORT_E_PINS_INIT
       //MDR_PORTE->RXTX   =
                MDR_PORTE->OE     = TESTBOARD_PORTE_OE;
                MDR_PORTE->FUNC   = TESTBOARD_PORTE_FUNC;
                MDR_PORTE->ANALOG = TESTBOARD_PORTE_ANALOG;
                MDR_PORTE->PULL   = TESTBOARD_PORTE_PULL;
                MDR_PORTE->PD     = TESTBOARD_PORTE_PD;
                MDR_PORTE->PWR    = TESTBOARD_PORTE_PWR;
                MDR_PORTE->GFEN   = TESTBOARD_PORTE_GFEN;

                #ifdef PORT_E_RXTX_INIT
                        MDR_PORTE->RXTX = TESTBOARD_PORT_E_RXTX_INIT_NUM;
                #endif
        #endif // End of PORT_E_PINS_INIT


        #ifdef PORT_F_PINS_INIT
        //MDR_PORTF->RXTX   =
                MDR_PORTF->OE     = TESTBOARD_PORTF_OE;
                MDR_PORTF->FUNC   = TESTBOARD_PORTF_FUNC;
                MDR_PORTF->ANALOG = TESTBOARD_PORTF_ANALOG;
                MDR_PORTF->PULL   = TESTBOARD_PORTF_PULL;
                MDR_PORTF->PD     = TESTBOARD_PORTF_PD;
                MDR_PORTF->PWR    = TESTBOARD_PORTF_PWR;
                MDR_PORTF->GFEN   = TESTBOARD_PORTF_GFEN;

                #ifdef PORT_F_RXTX_INIT
                        MDR_PORTF->RXTX = TESTBOARD_PORT_F_RXTX_INIT_NUM;
                #endif
        #endif // End of PORT_F_PINS_INIT
#endif
#ifdef REAL_DEVICE
        #ifdef PORT_A_PINS_INIT
                MDR_PORTA->OE     = REAL_DEVICE_PORTA_OE;
                MDR_PORTA->FUNC   = REAL_DEVICE_PORTA_FUNC;
                MDR_PORTA->ANALOG = REAL_DEVICE_PORTA_ANALOG;
                MDR_PORTA->PULL   = REAL_DEVICE_PORTA_PULL;
                MDR_PORTA->PD     = REAL_DEVICE_PORTA_PD;
                MDR_PORTA->PWR    = REAL_DEVICE_PORTA_PWR;
                MDR_PORTA->GFEN   = REAL_DEVICE_PORTA_GFEN;

                #ifdef PORT_A_RXTX_INIT
                        MDR_PORTA->RXTX = REAL_DEVICE_PORT_A_RXTX_INIT_NUM;
                #endif
        #endif // End of PORT_A_PINS_INIT


        #ifdef PORT_B_PINS_INIT
                MDR_PORTB->OE     = REAL_DEVICE_PORTB_OE;
                MDR_PORTB->FUNC   = REAL_DEVICE_PORTB_FUNC;
                MDR_PORTB->ANALOG = REAL_DEVICE_PORTB_ANALOG;
                MDR_PORTB->PULL   = REAL_DEVICE_PORTB_PULL;
                MDR_PORTB->PD     = REAL_DEVICE_PORTB_PD;
                MDR_PORTB->PWR    = REAL_DEVICE_PORTB_PWR;
                MDR_PORTB->GFEN   = REAL_DEVICE_PORTB_GFEN;

                #ifdef PORT_B_RXTX_INIT
                        MDR_PORTB->RXTX = REAL_DEVICE_PORT_B_RXTX_INIT_NUM;
                #endif
        #endif // End of PORT_B_PINS_INIT


        #ifdef PORT_C_PINS_INIT
        //MDR_PORTC->RXTX   =
                MDR_PORTC->OE     = REAL_DEVICE_PORTC_OE;
                MDR_PORTC->FUNC   = REAL_DEVICE_PORTC_FUNC;
                MDR_PORTC->ANALOG = REAL_DEVICE_PORTC_ANALOG;
                MDR_PORTC->PULL   = REAL_DEVICE_PORTC_PULL;
                MDR_PORTC->PD     = REAL_DEVICE_PORTC_PD;
                MDR_PORTC->PWR    = REAL_DEVICE_PORTC_PWR;
                MDR_PORTC->GFEN   = REAL_DEVICE_PORTC_GFEN;

                #ifdef PORT_C_RXTX_INIT
                        MDR_PORTC->RXTX = REAL_DEVICE_PORT_C_RXTX_INIT_NUM;
                #endif
       #endif // End of PORT_C_PINS_INIT


        #ifdef PORT_D_PINS_INIT
                MDR_PORTD->OE     = REAL_DEVICE_PORTD_OE;
                MDR_PORTD->FUNC   = REAL_DEVICE_PORTD_FUNC;
                MDR_PORTD->ANALOG = REAL_DEVICE_PORTD_ANALOG;
                MDR_PORTD->PULL   = REAL_DEVICE_PORTD_PULL;
                MDR_PORTD->PD     = REAL_DEVICE_PORTD_PD;
                MDR_PORTD->PWR    = REAL_DEVICE_PORTD_PWR;
                MDR_PORTD->GFEN   = REAL_DEVICE_PORTD_GFEN;

                #ifdef PORT_D_RXTX_INIT
                        MDR_PORTD->RXTX = REAL_DEVICE_PORT_D_RXTX_INIT_NUM;
                #endif
        #endif // End of PORT_D_PINS_INIT


        #ifdef PORT_E_PINS_INIT
       //MDR_PORTE->RXTX   =
                MDR_PORTE->OE     = REAL_DEVICE_PORTE_OE;
                MDR_PORTE->FUNC   = REAL_DEVICE_PORTE_FUNC;
                MDR_PORTE->ANALOG = REAL_DEVICE_PORTE_ANALOG;
                MDR_PORTE->PULL   = REAL_DEVICE_PORTE_PULL;
                MDR_PORTE->PD     = REAL_DEVICE_PORTE_PD;
                MDR_PORTE->PWR    = REAL_DEVICE_PORTE_PWR;
                MDR_PORTE->GFEN   = REAL_DEVICE_PORTE_GFEN;

                #ifdef PORT_E_RXTX_INIT
                        MDR_PORTE->RXTX = REAL_DEVICE_PORT_E_RXTX_INIT_NUM;
                #endif
        #endif // End of PORT_E_PINS_INIT


        #ifdef PORT_F_PINS_INIT
        //MDR_PORTF->RXTX   =
                MDR_PORTF->OE     = REAL_DEVICE_PORTF_OE;
                MDR_PORTF->FUNC   = REAL_DEVICE_PORTF_FUNC;
                MDR_PORTF->ANALOG = REAL_DEVICE_PORTF_ANALOG;
                MDR_PORTF->PULL   = REAL_DEVICE_PORTF_PULL;
                MDR_PORTF->PD     = REAL_DEVICE_PORTF_PD;
                MDR_PORTF->PWR    = REAL_DEVICE_PORTF_PWR;
                MDR_PORTF->GFEN   = REAL_DEVICE_PORTF_GFEN;

                #ifdef PORT_F_RXTX_INIT
                        MDR_PORTC->RXTX = REAL_DEVICE_PORT_F_RXTX_INIT_NUM;
                #endif
        #endif // End of PORT_F_PINS_INIT
#endif
#ifdef TEST_BOARD_DEVELOPMENT
        #ifdef PORT_A_PINS_INIT
                MDR_PORTA->OE     = PORT_A_OE;
                MDR_PORTA->FUNC   = PORT_A_FUNC;
                MDR_PORTA->ANALOG = PORT_A_AD;
                MDR_PORTA->PULL   = PORT_A_PULL;
                MDR_PORTA->PD     = PORT_A_PD;
                MDR_PORTA->PWR    = PORT_A_PWR;
                MDR_PORTA->GFEN   = PORT_A_GFEN;

                #ifdef PORT_F_RXTX_INIT
                        MDR_PORTC->RXTX = PORT_A_RXTX_INIT_NUM;
                #endif
        #endif // End of PORT_A_PINS_INIT


        #ifdef PORT_B_PINS_INIT
                MDR_PORTB->OE     = PORT_B_OE;
                MDR_PORTB->FUNC   = PORT_B_FUNC;
                MDR_PORTB->ANALOG = PORT_B_AD;
                MDR_PORTB->PULL   = PORT_B_PULL;
                MDR_PORTB->PD     = PORT_B_PD;
                MDR_PORTB->PWR    = PORT_B_PWR;
                MDR_PORTB->GFEN   = PORT_B_GFEN;

                #ifdef PORT_F_RXTX_INIT
                        MDR_PORTC->RXTX = PORT_B_RXTX_INIT_NUM;
                #endif
        #endif // End of PORT_B_PINS_INIT


        #ifdef PORT_C_PINS_INIT
        //MDR_PORTC->RXTX   =
                MDR_PORTC->OE     = PORT_C_OE;
                MDR_PORTC->FUNC   = PORT_C_FUNC;
                MDR_PORTC->ANALOG = PORT_C_AD;
                MDR_PORTC->PULL   = PORT_C_PULL;
                MDR_PORTC->PD     = PORT_C_PD;
                MDR_PORTC->PWR    = PORT_C_PWR;
                MDR_PORTC->GFEN   = PORT_C_GFEN;

                #ifdef PORT_F_RXTX_INIT
                        MDR_PORTC->RXTX = PORT_C_RXTX_INIT_NUM;
                #endif
        #endif // End of PORT_C_PINS_INIT


        #ifdef PORT_D_PINS_INIT
                MDR_PORTD->OE     = PORT_D_OE;
                MDR_PORTD->FUNC   = PORT_D_FUNC;
                MDR_PORTD->ANALOG = PORT_D_AD;
                MDR_PORTD->PULL   = PORT_D_PULL;
                MDR_PORTD->PD     = PORT_D_PD;
                MDR_PORTD->PWR    = PORT_D_PWR;
                MDR_PORTD->GFEN   = PORT_D_GFEN;

                #ifdef PORT_F_RXTX_INIT
                        MDR_PORTC->RXTX = PORT_D_RXTX_INIT_NUM;
                #endif
        #endif // End of PORT_D_PINS_INIT


        #ifdef PORT_E_PINS_INIT
       //MDR_PORTE->RXTX   =
                MDR_PORTE->OE     = PORT_E_OE;
                MDR_PORTE->FUNC   = PORT_E_FUNC;
                MDR_PORTE->ANALOG = PORT_E_AD;
                MDR_PORTE->PULL   = PORT_E_PULL;
                MDR_PORTE->PD     = PORT_E_PD;
                MDR_PORTE->PWR    = PORT_E_PWR;
                MDR_PORTE->GFEN   = PORT_E_GFEN;

                #ifdef PORT_F_RXTX_INIT
                        MDR_PORTC->RXTX = PORT_E_RXTX_INIT_NUM;
                #endif
        #endif // End of PORT_E_PINS_INIT


        #ifdef PORT_F_PINS_INIT
        //MDR_PORTF->RXTX   =
                MDR_PORTF->OE     = PORT_F_OE;
                MDR_PORTF->FUNC   = PORT_F_FUNC;
                MDR_PORTF->ANALOG = PORT_F_AD;
                MDR_PORTF->PULL   = PORT_F_PULL;
                MDR_PORTF->PD     = PORT_F_PD;
                MDR_PORTF->PWR    = PORT_F_PWR;
                MDR_PORTF->GFEN   = PORT_F_GFEN;

                #ifdef PORT_F_RXTX_INIT
                        MDR_PORTC->RXTX = PORT_F_RXTX_INIT_NUM;
                #endif
        #endif // End of PORT_F_PINS_INIT
#endif

}






